name: KBOT-CICD

on:
  push:
    branches:
      - "develop"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      APP: kbot
      REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need full history with tags

      - name: Run test
        run: make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: make image

      # - name: Image full name
      #   id: image-full-name
      #   run: echo "name=$(make image-tag)" >> "$GITHUB_OUTPUT"

      # - name: Dive
      #   uses: ${{ steps.image-full-name.name }}

      - name: Push
        run: make push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need full history with tags

      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - uses: mikefarah/yq@v4.43.1
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -am "update version $VERSION"
          git push
