name: KBOT-CICD

on:
  push:
    branches:
      - develop
      - "releases/**"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need full history with tags

      - name: Run test
        run: make test

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make image

      - name: Push
        run: make push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need full history with tags

      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - uses: mikefarah/yq@v4.43.1
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add helm/values.yaml
          git commit -m "update version $VERSION"
          git push
