name: KBOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    env:
      APP: kbot
      REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need full history with tags

      - name: Run test
        run: make test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: make image

      - name: Image full name
        id: image-full-name
        run: echo "name=$(make image-tag)" >> "$GITHUB_ENV"

      - name: Dive
        uses: ${{ steps.image-full-name.name }}

      - name: Build and push
        run: make image push
